### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MaggieChege**

### CODE REVIEW

**Comment by petermwash** [comment]
@MaggieChege 
- To better how you write your commit message, use this convetion [Feature #161173958] Added doc type each page
- You should create more pull request for each task you work on.

**Comment by MaggieChege** [comment]
@petermwash. Hadn't noticed that. I'll definitely include those changes in the next challenge. Thanks.

**Comment by petermwash** [comment]
Cool, All the best in your remaining challenges.

**Comment by MaggieChege** [comment]
Thanks

**Comment by petermwash** [comment]
Okay, if you get stuck or you are unfeel free to reach out.

**Comment by petermwash** [comment]
no sure*

**Pull request merged**
